/*
 * Copyright (c) 2011 Qualcomm Atheros, Inc.
 * All Rights Reserved.
 * Qualcomm Atheros Confidential and Proprietary.
 * $ATH_LICENSE_TARGET_C$
 */

#ifndef __CDR_BGR_H__
#define __CDR_BGR_H__


typedef enum {
    CDR_SELECT_REQUEST = 3,
    CDR_CONNECT_REQUEST,
    CDR_CONNECT_TIMEOUT,
    CDR_SOCK_OPEN_REQUEST,
    CDR_SOCK_BIND_REQUEST,
    CDR_SOCK_LISTEN_REQUEST,
    CDR_SOCK_ACCEPT_REQUEST,
    CDR_SOCK_CONNECT_REQUEST,
    CDR_SOCK_SETSOCKOPT_REQUEST,
    CDR_SOCK_GETSOCKOPT_REQUEST,
    CDR_SOCK_SEND_REQUEST,
    CDR_SOCK_SENDTO_REQUEST,
    CDR_SOCK_RECV_REQUEST,
    CDR_SOCK_RECVFROM_REQUEST,
    CDR_SOCK_CLOSE,
    CDR_MISC_WPS_INIT,
    CDR_MISC_WPS_SET_ATTRS,
    CDR_MISC_WPS_CANCEL,
    CDR_TRANSMIT_BUF_ALLOC,    
    CDR_GET_BP_INFO,
    CDR_READY,
    CDR_FREE_DATA_BUFFER,
    CDR_MISC_I2S_INIT,
    CDR_MISC_I2S_RCV,
    CDR_MISC_I2S_XMIT,
    CDR_MISC_I2S_RCV_CONTROL,
    CDR_CRYPTO_REQUEST,
    CDR_DBG_PRINT,
} CDR_BGR_CMD_TYPE;

#endif
